### PR TITLE
Update Installation Docs

### LINKED ISSUE #2319: Import Error ('compat') after upgrading from scancode-toolkit 3.2.0 to 3.2.3 via pip3
### Description

I was using scancode-toolkit 3.2.0 in an virtual-env on Python 3.6.12 succesfully.
Now I got a message, that 3.2.3 is available.
I upgraded to 3.2.3 with 'pip3 install scancode-toolkit -U'.

The upgrade rans without errors.

When I then try to run scancode with 'scancode --version' I get the error message:

ImportError: cannot import name 'compat'

### How To Reproduce

see above

### System configuration

* What OS are you running on? Ubuntu 20.04 LTS in an HyperV-VM

Any ideas? I am not very familiar with this Python stuff and just followed the installation instructions at "https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#pip-install" to get scancode running (which does until now :-) )

Regards, Thorsten

### LINKED ISSUE #2324: missing typecode-libmagic dependency
### Description

> Please leave a brief description of the bug or feature request:

missing dependency during installation (typecode-libmagic)

### How To Reproduce

> Tell us how to reproduce the issue. 

1. install scancode-toolkit with `pip` following the instructions in the docs
2. launch `scancode -h`
3. you get the following error:

```Traceback (most recent call last):
  File "/home/user/venv-scancode/bin/scancode", line 5, in <module>
    from scancode.cli import scancode
  File "/home/user/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 144, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/plugincode/__init__.py", line 217, in load_plugins
    mgr_setup = manager.setup()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/plugincode/__init__.py", line 241, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/home/user/venv-scancode/lib/python3.6/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/venv-scancode/lib/python3.6/site-packages/summarycode/generated.py", line 40, in <module>
    import typecode.contenttype
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/__init__.py", line 27, in <module>
    from typecode.contenttype import get_type
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/contenttype.py", line 56, in <module>
    from typecode import magic2
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/magic2.py", line 226, in <module>
    libmagic = load_lib()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/magic2.py", line 108, in load_lib
    'CRITICAL: libmagic DLL and is magic database are not installed. '
Exception: CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available.
```
4. to solve the issue, you have to run `pip install typecode-libmagic`

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 3.2.3
* What installation method was used to install/run scancode? pip

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
Fixes #2319 #2324 by updating installation documentation of the
pip install section. Also updates repository level INSTALL file
to have docker install instructions and fixes other minor typos.

Signed-off-by: Ayan Sinha Mahapatra <ayansmahapatra@gmail.com>

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

### CODE REVIEW

**Review by pombredanne — APPROVED** [review]
Thanks!
LGTM and merging now
