### ISSUE TITLE
Import Error ('compat') after upgrading from scancode-toolkit 3.2.0 to 3.2.3 via pip3

### ISSUE THREAD

**Issue by tgodau** [nexB/scancode-toolkit#2319]
### Description

I was using scancode-toolkit 3.2.0 in an virtual-env on Python 3.6.12 succesfully.
Now I got a message, that 3.2.3 is available.
I upgraded to 3.2.3 with 'pip3 install scancode-toolkit -U'.

The upgrade rans without errors.

When I then try to run scancode with 'scancode --version' I get the error message:

ImportError: cannot import name 'compat'

### How To Reproduce

see above

### System configuration

* What OS are you running on? Ubuntu 20.04 LTS in an HyperV-VM

Any ideas? I am not very familiar with this Python stuff and just followed the installation instructions at "https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#pip-install" to get scancode running (which does until now :-) )

Regards, Thorsten

**Comment by pombredanne** [comment]
@tgodau The way to install scancode from pip has changed a bit in this new version:
You need to install `scancode-toolkit[full]` and not just `scancode-toolkit`
Do you mind to try this?
And yes the doc needs to be updated ASAP.

**Comment by pombredanne** [comment]
@jyang do you agree that this would be the most likely issue?

**Comment by tgodau** [comment]
Thanks for the reply.

A 'pip3 install scancode-toolkit[full] -U' runs well, but doesn't solve the problem:

`# scancode --version
Traceback (most recent call last):
  File "/home/vmuser/venv-scancode/bin/scancode", line 5, in <module>
    from scancode.cli import scancode
  File "/home/vmuser/venv-scancode/lib/python3.6/site-packages/scancode/__init__.py", line 38, in <module>
    from commoncode import compat
ImportError: cannot import name 'compat'`

**Comment by pombredanne** [comment]
@tgodau could you try to first uninstall scancode then?

And/or separately try to create a virtualenv:
1. create a new directory somewhere and cd to it
2. `python3.6 -m venv .`
3. `source bin/activate`
4. `pip install scancode-toolkit[full]`

**Comment by JonoYang** [comment]
@pombredanne fwiw I installed scancode v 3.2.0 in an empty venv, run `scancode -h` to make sure it works, then run `pip install scancode-toolkit -U` and I get the same error as @tgodau . I had to first uninstall scancode toolkit from the venv, then run `pip install scancode-toolkit[full]` in order to run the latest version of scancode from pip.

**Comment by tgodau** [comment]
@jyang and @pombredanne, thank you guys for the valuable hints.

A `pip3 uninstall scancode-toolkit` inside my virtualenv followed by a `pip3 install scancode-toolkit[full]` did it.

All seems to work well now :-D

Regards, Thorsten

**Comment by pombredanne** [comment]
@tgodau Great! Allow me to keep this open so we can update the doc or FAQ accordingly.
